apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: mongors1
  name: mongors1
spec:
  ports:
  - name: mongors1
    port: 27017
    targetPort: 27017
  selector:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: mongors1
status:
  loadBalancer: {}