apiVersion: {{ default "extensions/v1beta1" .Values.deploymentApiVersion }}
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: indexer-mongos1
  name: indexer-mongos1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      release: {{ .Release.Name }}
      service: indexer-mongos1
  serviceName: indexer-mongos1
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
        service: indexer-mongos1
      name: indexer-mongos1
    spec:
      volumes:
      - name: init
        configMap:
          defaultMode: 0755
          name: mongodb-configmap-init
      containers:
      - name: indexer-mongos1
        image: mongo
        env:
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: init
          mountPath: /init
        command: ["/bin/bash","-c"]
        args:
        - source /init/on-start.sh "s1";
        env:
        - name: keyfile
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}
              key: keyfile
      restartPolicy: Always
      enableServiceLinks: false