apiVersion: {{ default "extensions/v1beta1" .Values.deploymentApiVersion }}
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: "{{ .Values.mongos.name }}"
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: "{{ .Values.mongos.service.name }}"
  name: "{{ .Values.mongos.service.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.mongos.name }}"
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      release: {{ .Release.Name }}
      service: "{{ .Values.mongos.service.name }}"
  serviceName: "{{ .Values.mongos.service.name }}"
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: "{{ .Values.mongos.name }}"
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
        service: "{{ .Values.mongos.service.name }}"
      name: "{{ .Values.mongos.service.name }}"
    spec:
      volumes:
      - name: scripts
        configMap:
          defaultMode: 0755
          name: mongo-configmap
          items:
          - key: on-start.sh
            path: on-start.sh
          - key: mongos.js
            path: mongos.js
      containers:
      - name: "{{ .Values.mongos.service.name }}"
        image: {{ .Values.common.image }}
        env:
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: scripts
          mountPath: /home/scripts
        command: ["/bin/bash","-c"]
        args:
        - source /home/scripts/on-start.sh "mongos";
        env:
        - name: KEYFILE
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}
              key: keyfile
      restartPolicy: Always
      enableServiceLinks: false