apiVersion: {{ default "extensions/v1beta1" .Values.deploymentApiVersion }}
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: "{{ .Values.configsvr.name }}"
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: "{{ .Values.configsvr.service.name }}"
  name: "{{ .Values.configsvr.service.name }}"
spec:
  replicas: {{ .Values.configsvr.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.configsvr.name }}"
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      release: {{ .Release.Name }}
      service: "{{ .Values.configsvr.service.name }}"
  serviceName: "{{ .Values.configsvr.service.name }}"
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: "{{ .Values.configsvr.name }}"
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
        service: "{{ .Values.configsvr.service.name }}"
      name: "{{ .Values.configsvr.service.name }}"
    spec:
      volumes:
      - name: datadir
        emptyDir: {}
      - name: scripts
        configMap:
          defaultMode: 0755
          name: mongo-configmap
          items:
          - key: on-start.sh
            path: on-start.sh
          - key: mongors1conf1.js
            path: mongors1conf1.js
      containers:
      - name: "{{ .Values.configsvr.service.name }}"
        image: {{ .Values.common.image }}
        env:
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: datadir
          mountPath: /data/db 
        - name: scripts
          mountPath: /home/scripts
        command: ["/bin/bash","-c"]
        args:
        - source /home/scripts/on-start.sh "config";
        env:
        - name: KEYFILE
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}
              key: keyfile
      restartPolicy: Always
      enableServiceLinks: false