version: '3'
services:
  mongorsn1:
    container_name: mongors1n1
    image: mongo
    command: mongod --keyFile /security/keyfile --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - D:/docker/timezone:/etc/localtime:ro
      - mongodb-data1:/data/db
      - mongodb-security:/security:ro
  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --keyFile /security/keyfile --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - D:/docker/timezone:/etc/localtime:ro
      - mongodb-config1:/data/db
      - mongodb-security:/security:ro
  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
    command: mongos --keyFile /security/keyfile --configdb mongors1conf/mongocfg1:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - D:/docker/timezone:/etc/localtime:ro
      - mongodb-security:/security:ro
volumes:
  mongodb-data1:
  mongodb-config1:
  mongodb-security:
    